plugins {
    id 'java'
}

group 'cat.nyaa'
version '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven {
        name 'NyaaCat'
        url 'https://ci.nyaacat.com/maven/'
    }
    maven {
        name 'Paper'
        url 'https://repo.papermc.io/repository/maven-public/'
    }
    maven { url "https://repo.dmulloy2.net/nexus/repository/public/" }
    maven { name 'aikar'; url 'https://repo.aikar.co/content/groups/aikar/' }
}


String majorVersion = 1
String minorVersion = 0
String minecraftVersion = "1.21.11"
String buildNumber = System.getenv("BUILD_NUMBER") == null ? "686936" : System.getenv("BUILD_NUMBER")

version = "$majorVersion.$minorVersion-$buildNumber"

dependencies {
    compileOnly('cat.nyaa:nyaacore:9.10')
    compileOnly('cat.nyaa:rpgitems:3.34-SNAPSHOT')
    compileOnly("io.papermc.paper:paper-api:$minecraftVersion-R0.1-SNAPSHOT")
    compileOnly group: "com.comphenix.protocol", name: "ProtocolLib", version: "5.1.0"

    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
}
